import { writable } from 'svelte/store';
import { Size, Rect, Point } from '../geometry/Geometry';

export const stoppedIDEditing	= writable<string | null>();
export const popupViewID		= writable<string | null>();
export const idEditing			= writable<string | null>();
export const idHere				= writable<string | null>();
export const dbLoadTime 		= writable<string | null>();
export const expanded			= writable<string[]>();
export const idsGrabbed			= writable<string[]>();
export const thingsArrived		= writable<boolean>();
export const showDetails		= writable<boolean>();
export const isBusy				= writable<boolean>();
export const bulkName			= writable<string>();
export const dbType				= writable<string>();
export const dotDiameter		= writable<number>();
export const lineStretch		= writable<number>();
export const lineGap			= writable<number>();
export const build				= writable<number>();
export const grephOffset		= writable<Point>();
export const graphRect  		= writable<Rect>();
export const windowSize  		= writable<Size>();
