import { Size, Rect, Point } from '../geometry/Geometry';
import { writable } from 'svelte/store';

export const idEditingStopped	= writable<string | null>();
export const popupViewID		= writable<string | null>();
export const idEditing			= writable<string | null>();
export const idHere				= writable<string | null>();
export const dbLoadTime 		= writable<string | null>();
export const expanded			= writable<string[]>();
export const idsGrabbed			= writable<string[]>();
export const thingsArrived		= writable<boolean>();
export const isBusy				= writable<boolean>();
export const dbType				= writable<string>();
export const titleFontFamily	= writable<string>();
export const titleFontSize		= writable<number>();
export const dotDiameter		= writable<number>();
export const lineStretch		= writable<number>();
export const lineGap			= writable<number>();
export const build				= writable<number>();
export const graphOffset		= writable<Point>();
export const graphRect  		= writable<Rect>();
export const windowSize  		= writable<Size>();
